#!/bin/sh -eu
#
# "gu": run "g"osub on "u"nix.
#
# Usage:
#   alias gu=./gu
#   gu test test/t1.go
#   gu build demo/wc.go
#   gu run demo/wc.go < Makefile

function compile() {
  T=$(basename $1 .go).bin
  (
    rm -f ___.*
    go run gosub.go < $1 > ___.defs.h 2>___.err || { cat ___.err ; exit 1 ; }
    clang-format -i --style=Google ___.*.c || true
    (
      echo '#include "___.defs.h"'
      echo 'void initvars() {'
      echo '}'
    ) > ___.initvars.c

    for x in ___.*.c
    do
      cc -g -c -Iruntime $x
    done
    ar qcs ___.a ___.*.o
    cc -g -I. -Iruntime -o $T runtime/runt.c runtime/bigmem.c  ___.a
    ls -l $T

    (
      echo '#include "___.defs.h"'
      echo 'void initvars() {'
      for x in $(nm $T  | awk '/__initvar_[1-9][0-9]*$/ {print $NF}')
      do
        echo "extern void $x();"
        echo "$x();"
      done
      echo '}'
    ) > ___.initvars.c

    cc -g -c -Iruntime ___.initvars.c
    ar rvcs ___.a ___.initvars.o
    cc -g -I. -Iruntime -o $T runtime/runt.c runtime/bigmem.c  ___.a
    ls -l $T
  ) >&2
  echo $T
}

case $2 in
  *.go ) : good ;;
  * )
    echo "Usage:  $0 build filename.go" >&2
    echo "Usage:  $0 test filename.go" >&2
    echo "Usage:  $0 run filename.go args..." >&2
    exit 13
esac

case $1 in
  build )
    compile $2
    ;;
  run )
    BIN=$(compile $2)
    shift
    shift
    $(dirname $BIN)/$(basename $BIN) "$@"
    ;;
  test )
    compile $2

    ./$(basename $2 .go).bin > $2.got
    grep '^// expect:' <$2 | sed 's;// expect:;;' > $2.want
    if diff -w $2.want $2.got
    then
      echo Good: $2 >&2
    else
      echo DIFFERENT: $2 >&2
      exit 1
    fi
    ;;
  * )
    echo "Usage:  $0 build filename.go" >&2
    echo "Usage:  $0 test filename.go" >&2
    echo "Usage:  $0 run filename.go args..." >&2
    exit 13
    ;;
esac
